name: Fetch CoinCap Data Daily (Python)

on:
  workflow_dispatch:     # Manual run
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

permissions:
  contents: write

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git reset

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests clickhouse-driver

      - name: Run CoinCap fetcher
        env:
          COINCAP_TOKEN: ${{ secrets.COINCAP_TOKEN }}
        run: python scripts/fetch_coincap.py

      - name: Force overwrite local state with remote
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin
          git reset --hard origin/main

      - name: Commit and push new CoinCap JSON
        run: |
          git add data/
          git commit -m "📈 Daily CoinCap data for $(date +%F)" || echo "No changes to commit"
          git push origin main --force

      - name: Test ClickHouse Connection
        run: echo "Connecting to ${{ secrets.CH_HOST }}:${{ secrets.CH_PORT }} as ${{ secrets.CH_USERNAME }}"

      - name: Ingest CoinCap data to ClickHouse
        env:
          CH_HOST: ${{ secrets.CH_HOST }}
          CH_PORT: ${{ secrets.CH_PORT }}
          CH_USER: ${{ secrets.CH_USERNAME }}
          CH_PASSWORD: ${{ secrets.CH_PASSWORD }}
          CH_DATABASE: ${{ secrets.CH_DB }}
        run: python scripts/ingest_to_clickhouse.py
