name: Fetch CoinCap Data Daily (Python)

on:
  workflow_dispatch:     # 👈 allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

permissions:
  contents: write

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 👈 Required for rebase to work properly

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run CoinCap fetcher
        env:
          COINCAP_TOKEN: ${{ secrets.COINCAP_TOKEN }}
        run: python scripts/fetch_coincap.py

      - name: Commit and push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main
          git add data/
          git commit -m "📈 Daily CoinCap data for $(date +%F)" || echo "No changes to commit"
          git push origin main
