name: Hello GitHub Actions

on: [push]  # Trigger the workflow on any push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
